app/manufacturer/urls.py
from django.urls import path, include

from .views import ManufacturerListView, ManuListView

app_name = 'manufacturer'

urlpatterns = [
  path('', ManufacturerListView.as_view(), name='manufacturer'),
  path('form_test', ManuListView.as_view(), name='form_test')
]

app/product/urls.py
from django.urls import path, include


from .views import MainCategoryView, SubCategoryView, ProductListView, ProductDetailView

app_name = 'product'

urlpatterns = [
  path('main_category/', MainCategoryView.as_view(), name='main_category'),
  path('sub_category/<str:slug>/', SubCategoryView.as_view(), name='main_sub_category'),
  path('products/<slug:slug>/', ProductListView.as_view(), name='products_list'),
  path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
]

app/static_pages/urls.py
from django.urls import path, include


from .views import HomePageView, AboutPageView, DeliveryPageView

app_name = 'static_pages'

urlpatterns = [
  path('', HomePageView.as_view(), name='home_page'),
  path('about/', AboutPageView.as_view(), name='about_page'),
  path('delivery/', DeliveryPageView.as_view(), name='delivery')
]

vodyanoy_back/urls.py
"""
URL configuration for vodyanoy_back project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/

"""



from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.static_pages.urls', namespace='static_pages')),
    path('users/', include('app.users.urls', namespace='users_app')),
    path('manufacturer/', include('app.manufacturer.urls', namespace='manufacturer_app')),
    
    path('catalog/', include('app.product.urls', namespace='catalog'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/news/models.py
from django.db import models

class News(models.Model):
  name = models.CharField(max_length=200, verbose_name='Название новости')
  desc = models.TextField(verbose_name='Текст новости')
  image = models.ImageField(upload_to='news/%Y/%m/%d', blank=True, null=True, verbose_name='Фото обложки новости')
  is_active = models.BooleanField(verbose_name='Отоброжение на сайте', default=True)
  slug = models.SlugField(max_length=255, verbose_name='слаг')
  
  class Meta:
    verbose_name = 'Новость'
    verbose_name_plural = 'Новости'
  
  def __str__(self) -> str:
    return self.name

app/product/models.py
from django.db import models
from django.urls import reverse



from ..users.utils import create_slug
from app.manufacturer.models import Manufacturer

from ..users.models import CustomUser




class MainCategory(models.Model):
  name = models.CharField(max_length=150, verbose_name='Название', unique=True)
  slug = models.SlugField(max_length=200, verbose_name='слаг', unique=True)
  photo = models.ImageField(verbose_name='Фото', upload_to='category_img/main_category_img', blank=True, null=True)
  
  class Meta:
    verbose_name = 'Главная категория'
    verbose_name_plural = 'Главные категории'
  
  def __str__(self) -> str:
    return self.name
  
  def get_absolute_url(self):
    return reverse('product:main_sub_category', kwargs={'slug': self.slug})
  
  def save(self, *args, **kwargs):
    self.slug = create_slug(self.name)
    return super().save(*args, **kwargs)



class SubCategory(models.Model):
  name = models.CharField(max_length=200, verbose_name='Название', unique=True)
  slug = models.SlugField(max_length=220, unique=True, verbose_name='слаг')
  photo = models.ImageField(verbose_name='Фото', upload_to='category_img/sub_category_img', blank=True, null=True)
  main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE, related_name='sub_categories', verbose_name='')
  
  class Meta:
    verbose_name = 'Подкатегория'
    verbose_name_plural = 'Подкатегории'
  
  def __str__(self) -> str:
    return self.name
  
  def get_absolute_url(self):
    return reverse('product:products_list', kwargs={'slug': self.slug})
  
  def save(self, *args, **kwargs):
    self.slug = create_slug(self.name)
    return super().save(*args, **kwargs)


class Product(models.Model):
  name = models.CharField(max_length=255, verbose_name='название')
  desc = models.TextField(max_length=800, verbose_name='Описание')
  price = models.IntegerField(verbose_name='Цена')
  photo = models.ImageField(verbose_name='Фото', upload_to='products_img')
  slug = models.SlugField(max_length=255, verbose_name='слаг')
  retro_bonus = models.PositiveIntegerField(default=1, verbose_name='Ретро бонус за покупку клиенту %')

  sub_category = models.ForeignKey(SubCategory, on_delete=models.PROTECT, related_name='products', verbose_name='подкатегория')
  manufacturer = models.ForeignKey(Manufacturer, related_name='products', on_delete=models.PROTECT, verbose_name='производитель')
  parametr = models.ManyToManyField('ProductParametr', related_name='product')
  
  class Meta:
    verbose_name = 'Товар'
    verbose_name_plural = 'Товары'
  
  
  def __str__(self) -> str:
    return self.name
  
  
  def save(self, *args, **kwargs):
    self.slug = create_slug(self.name)
    return super().save(*args, **kwargs)
  
  def get_absolute_url(self):
    return reverse('product:product_detail', kwargs={'slug': self.slug})
  
  def give_retro_to_client(self) -> int:
    return int(self.retro_bonus * self.price / 100)
  
  def apply_retro_bonus(self, user: CustomUser):
    user.user_profile.retro_bonus_balance += self.give_retro_to_client()
    user.user_profile.save()



class ProductParametr(models.Model):
  hit = models.BooleanField(default=False, verbose_name='Статус ХИТа продаж')
  new = models.BooleanField(default=False, verbose_name='Статус новинки')
  discount = models.IntegerField(default=0, blank=True, null=True, verbose_name='Скидка на товар')
  power= models.IntegerField(verbose_name='Мощность', blank=True, null=True)
  
  class Meta:
    verbose_name = 'Параметры товара'
    verbose_name_plural = 'Параметры товаров'
    
  def __str__(self) -> str:
    return f'{self.hit}/{self.new}/{self.discount}/{self.power}'



class ProductPhoto(models.Model):
  product = models.ForeignKey(Product, related_name='product_photos', verbose_name='Фотографии товара', on_delete=models.CASCADE)
  title = models.CharField(max_length=20, verbose_name='Название фото')
  photo = models.ImageField(verbose_name='Фото', upload_to='products_img/more')
  
  class Meta:
    verbose_name = 'verbose_name'
    verbose_name_plural = 'verbose_name_plural'
  
  
  def __str__(self):
    return self.title

app/static_pages/models.py
from django.db import models






class SpecialOffer(models.Model):
  name = models.CharField(max_length=150, verbose_name='Название')
  image = models.ImageField(verbose_name='Фото', upload_to='special_offers/%Y/%m', help_text='Максимальное разрешение изображения 2400х600px')
  
  class Meta:
    verbose_name = 'Слайдер на главной странице'
    verbose_name_plural = 'Слайдер на главной странице'

  def __str__(self) -> str:
    return self.name



# class Brands(models.Model):
#   name = models.CharField(max_length=200, verbose_name='Название бренда')
#   image = models.ImageField(verbose_name='Лого бренда', upload_to='', blank=True, null=True, help_text='Перед загрузкой удалить фон у фото')
  
#   class Meta:
#     verbose_name = 'Бренд'
#     verbose_name_plural = 'Бренды'
  
#   def __str__(self) -> str:
#     return self.name



class AboutInfo(models.Model):
  name = models.CharField(max_length=200, verbose_name='название пункта')
  desc = models.TextField(verbose_name='Описание пункта')
  
  class Meta:
    verbose_name = 'Инфо О нас'
    verbose_name_plural = 'Инфо О нас'
  
  def __str__(self) -> str:
    return self.name

app/static_pages/views.py
from typing import Any
from django.shortcuts import render



from ..news.models import News
from ..product.models import MainCategory, SubCategory, Product
from ..manufacturer.models import Manufacturer
# from .mixins import StaticPageMixin

from .models import SpecialOffer
from django.views.generic.base import TemplateView





class HomePageView(TemplateView):
  template_name = 'main_page/main_page.html'
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = 'Магазин инженерной сантехники'
    context['slider_images'] = SpecialOffer.objects.all()
    context['news_list'] = News.objects.all()[:8]
    context['brand_list'] = Manufacturer.objects.all()[:5]
    context['product_list'] = Product.objects.all()[:4]
    
    return context


class AboutPageView(TemplateView):
  template_name = 'static_page/about_page.html'
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = 'О компании'
    context['sub_categories'] = SubCategory.objects.all()
    return context


class DeliveryPageView(TemplateView):
  template_name = 'static_page/delivery_page.html'
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = 'Бесплатная Доставка в компании '
    return context

app/static_pages/templates/about_main_page.html
{% load static %}


<section class="about">
  <div class="container">
    <div class="about-content">
      <aside class="about-left">
        <div class="left-content">
          <h3 class="left-title">2K</h3>
          <p class="left-desc">наименований продукции</p>
        </div>
        <div class="left-content">
          <div class="left-content">
            <h3 class="left-title">30</h3>
            <p class="left-desc">брендов работают&nbsp;с&nbsp;нами</p>
          </div>
        </div>
      </aside>
      <aside class="about-right">
        <div class="rigth-content">
          <h3 class="right-title">Мы не просто продаем товары для ванной - мы помогаем вам&nbsp;найти&nbsp;лучшее&nbsp;решение.</h3>
        </div>
        <div class="about_advantage__top">
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/transport.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">ДОСТАВКА</h4>
              <p class="advantage__item_desc">Доставим товар в удобное для вас время</p>
            </div>
          </div>
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/car.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">САМОВЫВОЗ</h4>
              <p class="advantage__item_desc">Вы&nbsp;можете&nbsp;самостоятельно забрать заказ в пункте самовывоза.</p>
            </div>
          </div>
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/dashboard.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">ШИРОКИЙ АССОРТИМЕНТ&nbsp;ТОВАРОВ</h4>
              <p class="advantage__item_desc">У нас найдется все.</p>
            </div>
          </div>
        </div>
        <div class="about_advantage__top">
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/support.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">КЛИЕНТСКИЙ СЕРВИС</h4>
              <p class="advantage__item_desc">Оказываем поддержку на всех этапах покупки товара</p>
            </div>
          </div>
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/thumb.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">ГАРАНТИЯ КАЧЕСТВА</h4>
              <p class="advantage__item_desc">Соответствуем требованиям и стандартам качества</p>
            </div>
          </div>
          <div class="advantage__item">
            <img class="advantage__item_img" src="{% static 'img/icon/about_icons/sales.svg' %}" alt="">
            <div class="item_content">
              <h4 class="advantage__item_title">АКЦИИ И СКИДКИ </h4>
              <p class="advantage__item_desc">Постоянным клиентам акции и скидки</p>
            </div>
          </div>
        </div>
      </aside>
    </div>
  </div>
</section>

app/static_pages/templates/base.html
{% load static %}
{% load head_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="shortcut icon" href="{% static 'img/icon/vod_logo.ico' %}" type="image/x-icon">
  <title>{% head_title page_title %}</title>
</head>
<body>

  {% include 'header.html' %}



  {% block content %}

  {% endblock %}

  
  {% include 'footer.html' %}
  <script type="module" src="{% static 'js/main.js' %}"></script>
</body>
</html>

app/static_pages/templates/brands.html
{% load static %}

<section class="our-brands">
  <div class="container">
    <div class="main_brands">
      <h2 class="section-title">Популярные бренды</h2>
      <div class="back-text brands_back_text">Brands</div>
      <div class="brands-container">
        {% for brand in brand_list %}
        <div class="brand_item">
          <a href="#">
            <img class="brand_img" src="{{brand.image.url}}" alt="{{brand.name}}">
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

app/static_pages/templates/footer.html
{% load static %}


<footer class="footer">
  <div class="container">
    <div class="footer_content">
      <div class="footer_content__info">
        <div class="header-logo">
          <img src="{% static 'img/logo/vod_logo.png' %}" alt="">
          <h2 class="logo-text">Водяной</h2>
        </div>
        <div class="social_media">
          <div class="social_media__title">Мы в социальных сетях</div>
          <div class="social_media__img">
            <a href="">
              <img src="{% static 'img/social_img/inst.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'img/social_img/face.png' %}" alt="">
            </a>
          </div>
        </div>
        <div class="social_media pay">
          <div class="social_media__title">Мы принимаем</div>
          <div class="social_media__img">
            <a href="">
              <img src="{% static 'img/payment_card/mir.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'img/payment_card/master-card.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'img/payment_card/visa.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
      <div class="footer_content_left">
        <div class="footer_content__info">
          <h3 class="content__title">ПОКУПАТЕЛЮ</h3>
          <div class="content__item">
            <a href="">Доставка</a>
          </div>
          <div class="content__item">
            <a href="">Оплата</a>
          </div>
          <div class="content__item">
            <a href="">Гарантии и возврат</a>
          </div>
          <div class="content__item">
            <a href="">Производители</a>
          </div>
          <div class="content__item">
            <a href="">Статьи</a>
          </div>
        </div>
        <div class="footer_content__info">
          <h3 class="content__title">КОМПАНИЯ</h3>
          <div class="content__item">
            <a href="">О нас</a>
          </div>
          <div class="content__item">
            <a href="">Контакты</a>
          </div>
          <div class="content__item">
            <a href="">Пользовательское соглашение</a>
          </div>
          <div class="content__item">
            <a href="">Политика конфиденциальности</a>
          </div>
          <div class="content__item">
            <a href="">Обратная связь</a>
          </div>
        </div>
        <div class="footer_content__info">
          <div class="footer_content__company">
            <h3 class="content__title">КОНТАКТЫ</h3>
            <div class="company__item">
              <img src="{% static 'img/contact_img/phone.png' %}" alt="">
              <a href="">+7 771 010 1288</a>
            </div>
            <div class="company__item">
              <img src="{% static 'img/contact_img/mail.png' %}" alt="">
              <a href="">info@vodyanoy.asia</a>
            </div>
            <div class="company__item">
              <img src="{% static 'img/contact_img/address.png' %}" alt="">
              <a href="">Сайрамская 85/1</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/static_pages/templates/header.html
{% load static %}
{% load product_tags %}
{% get_main_categories as main_categories %}


<header class="header">
  <div class="container">
    <div class="header-top">
      <a href="{% url 'static_pages:home_page' %}">
        <div class="header-logo">
          <img src="{% static 'img/logo/vod_logo.png' %}" alt="">
          <h1 class="logo-text">Водяной</h1>
        </div>
      </a>
      <nav class="header-nav">
        <ul>
          <li><a href="{% url 'static_pages:about_page' %}">О нас</a></li>
          <li><a href="{% url 'manufacturer_app:manufacturer' %}">Производители</a></li>
          <li><a href="#">Гарантии и возврат</a></li>
          <li><a href="{% url 'static_pages:delivery' %}">Доставка</a></li>
          <li><a href="#">Оплата</a></li>
          <li><a href="#">Контакты</a></li>
        </ul>
      </nav>
      <div class="regiter-login">
        <a href="">Вход &nbsp;/&nbsp;</a><a href="">&nbsp;Регистрация</a>
      </div>
    </div>
    <div class="header-bottom">
      <div class="header-bottom__left">
        <div class="header-bottom__left catalog_btn">
          <a href="{% url 'product:main_category' %}"><img src="{% static 'img/header_img/burger.png' %}" alt="">
            <h2 class="catalog-title">Каталог товаров</h2>
          </a>
          <div class="header_catalog_view">
            {% for main_category in main_categories %}
            <a class="main_category__item" href={{main_category.get_absolute_url}}>
              <img src="{{main_category.photo.url}}" alt="">{{main_category.name|upper}}
            </a>
            {% endfor %}
        </div>
        </div>
        <div class="search-form">
          <input class="search-form__text" type="text" placeholder="Поиск товаров и брендов">
          <button class="search-form__btn"><img class="search-form__img" src="{% static 'img/header_img/search_1.png' %}" alt=""></button>
        </div>
      </div>
      <div class="header-bottom__rigth">
        <div class="call-phone">
          <div class="call-phone__number">8-800-2000-22-22</div>
          <div class="call-phone__text">Вам перезвонить?</div>
        </div>
        <div class="header-bottom__tools">
          <div class="tools__item">
            <img class="tools__img" src="{% static 'img/header_img/heart.png' %}" alt="">
            <a href="">Избранное</a>
          </div>
          <div class="tools__item">
            <img class="tools__img" src="{% static 'img/header_img/basket.png' %}" alt="">
            <a href="">Корзина</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/static_pages/templates/main_page_catalog.html
{% load static %}


<section class="section-slider">
  <div class="slider-container">
    <div class="slider-top">
      <img class="arrow arrow-right" src="{% static 'img/icon/arrow.png' %}" alt="">
      <div class="slider">
        {% for photo in slider_images %}
          <img class="slider__image{% if forloop.first %} block {% endif %}" src="{{ photo.image.url }}" alt="{{ photo.name}}">
        {% endfor %}
      </div>
      <img class="arrow arrow-left" src="{% static 'img/icon/arrow.png' %}" alt="">
    </div>
    <div class="slider-bottom">
    </div>
  </div>
</section>


<section class="main-catalog">
  <div class="container">
    <div class="main-catalog__container">
      <div class="main-catalog__container_top">
        <div class="main-catalog__title title_active">
          <a href="">ХИТЫ ПРОДАЖ</a>
        </div>
        <div class="main-catalog__title">
          <a href="">НОВИНКИ</a>
        </div>
        <div class="main-catalog__title">
          <a href="">% СКИДКИ</a>
        </div>
      </div>
      <div class="main-catalog__container_bottom">
        <div class="main-catalog__subtitle">
          <a href="">Все</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Ванны</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Душ</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Душевые углы</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Мебель для ванных комнат</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Полотенцесушители</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Санфаянс</a>
        </div>
        <div class="main-catalog__subtitle">
          <a href="">Смесители</a>
        </div>
      </div>
    </div>
    <div class="main-catalog__products">
      <div class="main-catalog__item">
        {% for product in product_list %}
          <div class="product">
            <a href="{{product.get_absolute_url}}">
              <img class="product__img" src="{{product.photo.url}}" alt="{{product.name}}">
              <div class="product-content">
                <h3 class="product__title">{{product.name}}</h3>
                <p class="product__desc">{{product.desc}}</p>
              </div>
              <div class="product_price">
                <div class="product_price__value">{{product.price}}&nbsp;</div>
                <div class="product_price__currency">&#x20b8;</div>
              </div>
            </a>
              <div class="product_btn">
                <button class="product__buy">Купить</button>
                <img class="add-to-favorite" src="{% static 'img/header_img/heart.png' %}" alt="">
              </div>
          </div>
        {% endfor %}
      </div>  
    </div>
  </div>
</section>

app/static_pages/templates/news_main.html
{% load static %}


<section class="news">
  <div class="container">
    <div class="news_container">
      <h2 class="section-title">Новости и события</h2>
      <div class="back-text news_main_back_text">News and events</div>
    </div>
    <div class="news_content">
      {% for news in news_list %}
        <div class="news__item">
          <a href="">
            <div class="news_item__img">
              <img src="{{news.image.url}}" alt="">
            </div>
            <div class="news_item__content">
              <h4 class="news_item_title">{{news.name}}</h4>
              <p class="news_item__desc">{{news.desc|truncatechars:50}}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
</section>